disabled_rules:
  - function_body_length
  - opening_brace # Conflicts with SwiftFormat
  - trailing_comma
excluded:
  - example/*/DerivedData/
  - example/*/Pods/
  - example/*/build/
  - example/node_modules/
  - node_modules/
